spring:
  cloud:
    stream:
      bindings:
        receiveOrderDetailsAndPublish-in-0:
          content-type: application/json 
          destination: orders-details-topic
        receiveOrderDetailsAndPublish-out-0:
          destination: inventory-updates-topic
          content-type: application/json
      function:
        definition: receiveOrderDetailsAndPublish
      kafka:
        binder:
          brokers: localhost:19092
  application:
    name: inventory-microservice
  datasource:
    password: password
    username: root
    url: jdbc:mysql://localhost:3306/inventory
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: '8082'
